repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        # Assumes that your shell's `python` command is linked to python3.6+
        language_version: python
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
