repos:
  # Ruff Python linter and formatter (configs in pyproject.toml)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 22f0422809455ec89ffdcf5a00170ba816e42ddb # frozen: v0.15.16
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix, --show-fixes] # enable lint fixes
      # Run the formatter
      - id: ruff-format
