[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "simulatingrisk"
description = "Agent-based modeling for simulations related to risk and rationality"
requires-python = ">=3.7"
license = {text = "Apache-2"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "mesa>=2.1",
]
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
version = {attr = "simulatingrisk.__version__"}
readme = {file = ["README.md"]}

[tool.setuptools.packages.find]
include = ["simulatingrisk"]
# exclude tests and notebooks

[project.optional-dependencies]
dev = ["pre-commit", "pytest", "pytest-cov"]

[tool.black]
line-length = 88
target-version = ['py38']
# include = ''
# extend-exclude = ''
