# shared utility code for analysis notebooks

import marimo as mo
import polars as pl
import altair as alt


def custom_boxplot(df):
    # custom box plot method using layered plots,
    # so that we can efficiently generate plots from statistics generated by polars

    # calculate risk group labels, for color
    plot_df = df.with_columns(
        risk_type=pl.when(pl.col.risk_attitude < 3)
        .then(pl.lit("Risk-Seeking"))
        .when(pl.col.risk_attitude < 7)
        .then(pl.lit("Risk-Moderate"))
        .otherwise(pl.lit("Risk-Averse"))
    )
    # create base chart to use across layers
    base_chart = alt.Chart(plot_df)

    # area chart for Q1 to Q3
    area_chart = base_chart.mark_rect(width=15).encode(
        y=alt.Y("Q1", axis=alt.Axis(offset=12)),
        y2="Q3",
        x=alt.X("risk_attitude:Q", title="Risk Attitude"),
        tooltip=["min", "max", "mean", "Q1", "median", "Q3"],
        # colors from tableau 10 https://vega.github.io/vega/docs/schemes/#tableau10
        # but specify order to make more logical/semantic
        color=alt.Color(
            "risk_type",
            title="Risk Attitude",
            sort=["Risk Inclined", "Risk Moderate", "Risk Avoidant"],
        ).scale(range=["#e45756", "#f58518", "#4c78a8"]),
    )
    # line chart for min-max spread
    # specifying a stroke for point on the line only adds the min point

    # set light/dark color depending on notebook theme
    line_stroke_color = " #52514e" if mo.app_meta().theme == "light" else "#c3c2b7"

    minmax_line_chart = base_chart.mark_line(
        point=alt.OverlayMarkDef(
            filled=False, shape="stroke", color=line_stroke_color, strokeWidth=2
        )
    ).encode(alt.Y("min"), alt.Y2("max"), x="risk_attitude:Q")
    # add a black stroke for the max
    max_marks = base_chart.mark_point(
        shape="stroke", size=55, color=line_stroke_color
    ).encode(
        y="max",
        x=alt.X("risk_attitude:Q"),
    )

    median_marks = base_chart.mark_point(
        shape="stroke", size=100, strokeWidth=1, color=line_stroke_color
    ).encode(y="median", x="risk_attitude:Q")

    # mean line ?
    mean_line_chart = base_chart.mark_line(
        interpolate="monotone", color=line_stroke_color, opacity=0.5
    ).encode(
        x=alt.X("risk_attitude:Q"),
        y=alt.Y("mean", title="Cumulative Payoff").scale(zero=False),
    )

    return (
        mean_line_chart + minmax_line_chart + area_chart + median_marks + max_marks
    ).resolve_axis("shared")


def plot_mean_quartiles(df, field, field_label, chart_title):
    # define a custom method to plot mean and quartiles for a specified simulation parameter
    # - currently payoff specific

    # takes a dataframe, the field in the dataframe for the simulation parameter, and displayable label for the field

    # create a selection filter bound to the legend
    selection = alt.selection_point(fields=[field], bind="legend")
    base_chart = alt.Chart(df)
    # curved line for the mean pyoff by risk attitude
    payoff_mean_chart = base_chart.mark_line(interpolate="monotone").encode(
        x=alt.X("risk_attitude", title="Risk Attitude", scale=alt.Scale(domain=[0, 9])),
        y=alt.Y(
            # leave hard-coded for now
            "mean",
            title="Cumulative Payoff (mean)",
            scale=alt.Scale(zero=False),
        ),
        color=alt.Color(f"{field}:N", title=field_label),
        opacity=alt.when(selection).then(alt.value(1.0)).otherwise(alt.value(0.4)),
    )
    # curved area chart for payoff quartile spread
    payoff_spread = base_chart.mark_area(interpolate="monotone").encode(
        x=alt.X("risk_attitude", title="Risk Attitude", scale=alt.Scale(domain=[0, 9])),
        y=alt.Y("Q3", scale=alt.Scale(zero=False)),
        y2="Q1",
        color=alt.Color(f"{field}:N", title=field_label),
        opacity=alt.when(selection).then(alt.value(0.3)).otherwise(alt.value(0.1)),
    )

    # combine the charts for multiple ways to view
    chart_payoff_title = chart_title.copy()
    chart_payoff_title["text"] = (
        f"{chart_title['text']} and {field_label} — Mean and Quartiles"
    )

    # display mean curve chart, payoff area chart, and mean layered with the payoff
    return (
        (payoff_mean_chart | payoff_spread | (payoff_mean_chart + payoff_spread))
        .add_params(selection)
        .resolve_legend(color="shared")
        .properties(title=chart_payoff_title)
    )
